apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command:
        - sleep
      args:
        - infinity

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: dockerhubcredentials
          mountPath: /kaniko/.docker/config.json  # Monta o arquivo de credenciais diretamente no caminho correto
        - name: jenkins-artifacts
          mountPath: /artifacts  # Montando o volume temporário para armazenar artefatos

  volumes:
    - name: dockerhubcredentials
      secret:
        secretName: docker-hub-credentials  # Nome do Secret com as credenciais Docker
    - name: jenkins-artifacts
      emptyDir: {}  # Volume temporário para armazenar artefatos durante o processo de build
