apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: jenkins
spec:
  terminationGracePeriodSeconds: 30  # Dá tempo para encerramento correto dos containers
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command: ["sleep"]
      args: ["infinity"]

    - name: buildah
      image: quay.io/buildah/stable:latest
      securityContext:
        runAsUser: 0  # Executa como root para evitar problemas de permissão
        privileged: true
        capabilities:
          add:
            - SETFCAP
            - SYS_ADMIN
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: jenkins-artifacts
          mountPath: /artifacts
    - name: helm
      image: alpine/helm:3.14.2
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: jenkins-artifacts
          mountPath: /artifacts

  volumes:
    - name: jenkins-artifacts
      persistentVolumeClaim:
        claimName: jenkins-artifacts  


  