apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: jenkins
spec:
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command: ["sleep"]
      args: ["infinity"]

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: dockerhubcredentials
          mountPath: /kaniko/.docker/config.json
          subPath: .dockerconfigjson  # SubPath para evitar conflitos
        - name: jenkins-artifacts
          mountPath: /artifacts

  volumes:
    - name: dockerhubcredentials
      secret:
        secretName: docker-hub-credentials
    - name: jenkins-artifacts
      emptyDir: {}