apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: jenkins
spec:
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command: ["sleep"]
      args: ["infinity"]

    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.14.0-debug
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: dockerhub-credentials
          mountPath: /kaniko/.docker/config.json
          subPath: config.json
          readOnly: true
        - name: dockerfile-storage
          mountPath: /workspace
  volumes:
    - name: dockerhub-credentials
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim

   