apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: jenkins
spec:
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command: ["sleep"]
      args: ["infinity"]

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=/mnt/data/kaniko/dockerfile",
            "--context=dir:///mnt/data/kaniko",
            "--destination=docker.io/israelxnp/teste03:0.0.1"]
      volumeMounts:
        - name: dockerhub-credentials
          mountPath: /kaniko/.docker
        - name: dockerfile-storage
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: dockerhub-credentials
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json  
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim

   