apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: jenkins
spec:
  containers:
    - name: python
      image: python:3.9.12-alpine3.15
      command: ["sleep"]
      args: ["infinity"]

    - name: buildah
      image: quay.io/buildah/stable:latest
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        privileged: true
      command: ["sleep"]
      args: ["infinity"]

   


  